query UserGroups {
    userGroups {
        id
        name
        event_date
        created_at
        avatar {
            id
            name
            url
        }
        userToGroups {
            id
            user {
                id
                pseudo
                avatar {
                    id
                    name
                    url
                }
                email
            }
        }
        discussions {
            id
            users {
                id
                pseudo
                avatar {
                    id
                    url
                }
            }
            userDiscussion {
                id
                pseudo
            }
        }
    }
}
